# -*- coding: utf-8 -*-
"""MINI ASSIGNMENT

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10zw--06GvpHfaPYfz0AWZUXIAGkRnH-r

# **Mini assignment**

# Create a DNA string of 10,000 characters and count the following A,T,G,C all combination of two characters
"""

import random as rn
R = [rn.choice(['A','T','G','C']) for i in range(10000)]
print(R)

DNA = '' .join(R)
DNA

DNA.count("A"),DNA.count("T"),DNA.count("C"),DNA.count("G")

DNA.count("AT"),DNA.count("TA")

DNA.count("AA")

DNA.count('GG'),DNA.count('TT'),DNA.count('CC'),DNA.count('AA')

DNA.count('GC'),DNA.count('CG'),DNA.count('TC'),DNA.count('CT')

DNA.count('TG'),DNA.count('GT'),DNA.count('AG'),DNA.count('GA')

DNA.count('AC'),DNA.count('CA'),DNA.count('TG'),DNA.count('GC'),

DNA.count('ATG'),DNA.count('AGT'),DNA.count('AAG'),DNA.count('AGA'),

DNA.count('TAG'),DNA.count('GAT'),DNA.count('AGC'),DNA.count('GTA'),

DNA.count('TCG'),DNA.count('CGT'),DNA.count('AGC'),DNA.count('GTA'),

DNA.count('TGC'),DNA.count('GTC'),DNA.count('ACG'),DNA.count('CGA')

